[build]
  publish   = "."            # serve from the repo root
  functions = "functions"    # look here for lambdas

# (optional) client‑side SPA redirect
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200

